title: Service Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.opmeteor.co.uk
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Core Service
      category: Voice
      description: The Backbone of the Voice Service
    - name: Web Console
      category: Voice
    - name: Web UI
      category: Voice
      description: ""
    - name: Mapping
      category: General
      description: ByWay Map Display
      partial: ""
    - name: Blue Book
      category: General
      description: Vehicle Info pages
      partial: https://bluebook.opmeteor.co.uk
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: false
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: General
      untitled: false
      closed: true
    - name: Voice
      closed: true
      description: Status of Communication Services
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: false
  useLargeHeaderDesign: false
